apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  project: default
  source:
    repoURL: https://github.com/benkorichard/argocd-test.git
    path: apps/ingress
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
