apps:
    - name: meta
      sourcePath: apps/cluster
default:
    destination:
        server: https://kubernetes.default.svc
    source:
        repoURL: https://github.com/benkorichard/argocd-test.git
        targetRevision: main