apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 4.7.1
appVersion: 4.7.1
dependencies:
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.7.1